server:
  port: 8080
  servlet:
    context-path: /
  # Allow connections from any IP for multi-system setup
  address: 0.0.0.0

spring:
  application:
    name: spruce-backend-server
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/spruce_db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:spruce_user}
    password: ${SPRING_DATASOURCE_PASSWORD:spruce_password_2024}
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_DIALECT:org.hibernate.dialect.MySQL8Dialect}
  
  security:
    user:
      name: admin
      password: admin123

# CORS configuration for multi-system access
cors:
  allowed-origins: 
    - http://localhost:3000
    - http://localhost:3001
    - http://192.168.1.*:3000
    - http://192.168.1.*:3001
    - http://10.0.0.*:3000
    - http://10.0.0.*:3001
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.spruce: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/spruce-server.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always






