server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: spruce-backend
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:spruce}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_DIALECT:org.hibernate.dialect.H2Dialect}
  
  security:
    user:
      name: admin
      password: admin123

logging:
  level:
    com.spruce: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/spruce-backend.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
